// Generated from the "Coms report" semantic model TMDL (table _PO_VIEW_), 2026-10-07.
// Labels are hand-reviewed expansions of the model names (abbreviations kept
// upper-case: PO, ETA, CRD, ...); edit them here, not in the grid.
// Regenerate when the model's columns change: export the model with
// `fab export "EMBEDDING PROD.Workspace/Coms report.SemanticModel"` and rebuild this list.

export type PoColumnType = 'string' | 'int64' | 'double' | 'dateTime';

export interface PoColumn {
  /** Model column name, also the DAX alias and the row key. */
  name: string;
  type: PoColumnType;
  /** Friendly header text; the model name stays available as a tooltip. */
  label: string;
}

/**
 * Every column of `_PO_VIEW_`, in model order. The six calculated placeholders
 * `_tbd_* = 1` are left out on purpose: they are constant 1 in every row.
 */
export const PO_COLUMNS: readonly PoColumn[] = [
  { name: '_line_type', type: 'string', label: 'Line Type' },
  { name: '_line_id', type: 'string', label: 'Line ID' },
  { name: '_shipped', type: 'double', label: 'Shipped' },
  { name: '_qnty_shipped_remaning', type: 'double', label: 'Qty Shipped Remaining' },
  { name: '_branch_bu', type: 'string', label: 'Branch / BU' },
  { name: '_supplier_code', type: 'string', label: 'Supplier Code' },
  { name: '_supplier_name', type: 'string', label: 'Supplier Name' },
  { name: '_po_no_ekporef', type: 'string', label: 'PO No. (EKPO Ref)' },
  { name: '_po_remarks', type: 'string', label: 'PO Remarks' },
  { name: '_commodity', type: 'string', label: 'Commodity' },
  { name: '_incoterms', type: 'string', label: 'Incoterms' },
  { name: '_incoterms_desc', type: 'string', label: 'Incoterms Description' },
  { name: '_pr_appr_date', type: 'dateTime', label: 'PR Approval Date' },
  { name: '_po_app_date', type: 'dateTime', label: 'PO Approval Date' },
  { name: '_po_creation_date', type: 'dateTime', label: 'PO Creation Date' },
  { name: '_po_recd_date', type: 'dateTime', label: 'PO Received Date' },
  { name: '_po_need_by_date', type: 'dateTime', label: 'PO Need-by Date' },
  { name: '_line_no', type: 'int64', label: 'Line No.' },
  { name: '_po_type', type: 'string', label: 'PO Type' },
  { name: '_incoterms_fo', type: 'string', label: 'Incoterms (FO)' },
  { name: '_shipment_serial_iss_job', type: 'string', label: 'Shipment Serial (ISS Job)' },
  { name: '_hbl_hawb', type: 'string', label: 'HBL / HAWB' },
  { name: '_mbl_mawb', type: 'string', label: 'MBL / MAWB' },
  { name: '_freight_unit_id', type: 'int64', label: 'Freight Unit ID' },
  { name: '_fo_id', type: 'int64', label: 'FO ID' },
  { name: '_fo_serial', type: 'string', label: 'FO Serial' },
  { name: '_shipment_link', type: 'string', label: 'Shipment Link' },
  { name: '_eqpt_type', type: 'string', label: 'Equipment Type' },
  { name: '_20_ft', type: 'int64', label: '20 ft Containers' },
  { name: '_40_ft', type: 'int64', label: '40 ft Containers' },
  { name: '_count_of_cont', type: 'int64', label: 'Container Count' },
  { name: '_teus', type: 'int64', label: 'TEUs' },
  { name: '_carrier', type: 'string', label: 'Carrier' },
  { name: '_arrival_date', type: 'dateTime', label: 'Arrival Date' },
  { name: '_del', type: 'dateTime', label: 'Delivery Date' },
  { name: '_departure_date', type: 'dateTime', label: 'Departure Date' },
  { name: '_departure_date_actual', type: 'dateTime', label: 'Departure Date Actual' },
  { name: '_crd_actual', type: 'dateTime', label: 'CRD Actual' },
  { name: '_crd_estimated', type: 'dateTime', label: 'CRD Estimated' },
  { name: '_crd', type: 'dateTime', label: 'CRD' },
  { name: '_goods_cleared_origin', type: 'dateTime', label: 'Goods Cleared Origin' },
  { name: '_goods_cleared_destination', type: 'dateTime', label: 'Goods Cleared Destination' },
  { name: '_pickup_date', type: 'dateTime', label: 'Pickup Date' },
  { name: '_cargo_ho', type: 'dateTime', label: 'Cargo Handover' },
  { name: '_eta', type: 'dateTime', label: 'ETA' },
  { name: '_eta_wakeo', type: 'dateTime', label: 'ETA (Wakeo)' },
  { name: '_etd', type: 'dateTime', label: 'ETD' },
  { name: '_etd_wakeo', type: 'dateTime', label: 'ETD (Wakeo)' },
  { name: '_full_etd', type: 'dateTime', label: 'Full ETD' },
  { name: '_pod_date', type: 'dateTime', label: 'POD Date' },
  { name: '_do_date', type: 'dateTime', label: 'DO Date' },
  { name: '_do_exp', type: 'dateTime', label: 'DO Expiry' },
  { name: '_pr_number', type: 'string', label: 'PR Number' },
  { name: '_pr_date', type: 'dateTime', label: 'PR Date' },
  { name: '_req_status', type: 'string', label: 'Request Status' },
  { name: '_spo_number', type: 'string', label: 'SPO Number' },
  { name: '_po_status', type: 'string', label: 'PO Status' },
  { name: '_grn_no', type: 'string', label: 'GRN No.' },
  { name: '_grn_status', type: 'string', label: 'GRN Status' },
  { name: '_addl_po', type: 'string', label: 'Additional PO' },
  { name: '_addl_po_grn', type: 'string', label: 'Additional PO GRN' },
  { name: '_days_delayed_eta', type: 'int64', label: 'Days Delayed ETA' },
  { name: '_days_delayed_etd', type: 'int64', label: 'Days Delayed ETD' },
  { name: '_etd_2_eta', type: 'int64', label: 'ETD to ETA' },
  { name: '_eta_2_del', type: 'int64', label: 'ETA to Delivery' },
  { name: '_nbd_2_del', type: 'int64', label: 'NBD to Delivery' },
  { name: '_client_id', type: 'int64', label: 'Client ID' },
  { name: '_client_name', type: 'string', label: 'Client Name' },
  { name: '_origin_port_pol', type: 'string', label: 'Origin Port (POL)' },
  { name: '_origin_port_name', type: 'string', label: 'Origin Port Name' },
  { name: '_origin_country', type: 'string', label: 'Origin Country' },
  { name: '_origin_region_org_reg', type: 'string', label: 'Origin Region' },
  { name: '_destination_port_code_dest', type: 'string', label: 'Destination Port Code' },
  { name: '_destination_port_name_dest', type: 'string', label: 'Destination Port Name' },
  { name: '_destination_country_code_dest', type: 'string', label: 'Destination Country Code' },
  { name: '_destination_country_dest', type: 'string', label: 'Destination Country' },
  { name: '_destination_region_reg', type: 'string', label: 'Destination Region' },
  { name: '_ship_remarks_updates', type: 'string', label: 'Ship Remarks Updates' },
  { name: '_ship_billing_remarks', type: 'string', label: 'Ship Billing Remarks' },
  { name: '_routed_by', type: 'string', label: 'Routed By' },
  { name: '_aux_charge_type', type: 'string', label: 'Aux Charge Type' },
  { name: '_aux_charge_form_no', type: 'string', label: 'Aux Charge Form No.' },
  { name: '_org_charges_aed', type: 'double', label: 'Origin Charges AED' },
  { name: '_dest_charges_aed', type: 'double', label: 'Destination Charges AED' },
  { name: '_frt_charges_aed', type: 'double', label: 'Freight Charges AED' },
  { name: '_aux_charges_aed', type: 'double', label: 'Aux Charges AED' },
  { name: '_p2p_value_aed', type: 'double', label: 'P2P Value AED' },
  { name: '_total_charges_aed', type: 'double', label: 'Total Charges AED' },
  { name: '_org_charges_usd', type: 'double', label: 'Origin Charges USD' },
  { name: '_dest_charges_usd', type: 'double', label: 'Destination Charges USD' },
  { name: '_frt_charges_usd', type: 'double', label: 'Freight Charges USD' },
  { name: '_aux_charges_usd', type: 'double', label: 'Aux Charges USD' },
  { name: '_p2p_value_usd', type: 'double', label: 'P2P Value USD' },
  { name: '_total_charges_usd', type: 'double', label: 'Total Charges USD' },
  { name: '_invoice_no', type: 'string', label: 'Invoice No.' },
  { name: '_invoice_issue_date', type: 'string', label: 'Invoice Issue Date' },
  { name: '_addl_issued_invoices', type: 'string', label: 'Additional Issued Invoices' },
  { name: '_addl_invoice_issue_date', type: 'string', label: 'Additional Invoice Issue Date' },
  { name: '_customs_invoice_aed', type: 'double', label: 'Customs Invoice AED' },
  { name: '_customs_invoice_usd', type: 'double', label: 'Customs Invoice USD' },
  { name: '_billing_status', type: 'string', label: 'Billing Status' },
  { name: '_mode', type: 'string', label: 'Mode' },
  { name: '_days_order_placement_lt', type: 'int64', label: 'Days Order Placement LT' },
  { name: '_days_supplier_production_lt', type: 'int64', label: 'Days Supplier Production LT' },
  { name: '_days_custom_clearance_lt', type: 'int64', label: 'Days Custom Clearance LT' },
  { name: '_days_iss_cont_booking_lt', type: 'int64', label: 'Days ISS Containers Booking LT' },
  { name: '_days_transit_lt', type: 'int64', label: 'Days Transit LT' },
  { name: '_e2e_total_lt', type: 'int64', label: 'E2E Total LT (days)' },
  { name: '_supplier_lead_time', type: 'int64', label: 'Supplier Lead Time' },
  { name: '_country_lead_time', type: 'int64', label: 'Country Lead Time' },
  { name: '_ontime_order_placement_perf', type: 'double', label: 'On-time Order Placement Performance' },
  { name: '_days_total_comm_perf', type: 'double', label: 'Days Total Commitment Performance' },
  { name: '_e2e_total_lead_time_perf', type: 'double', label: 'E2E Total Lead Time Performance' },
  { name: '_iss_cont_booking_perf', type: 'double', label: 'ISS Containers Booking Performance' },
  { name: '_supplier_committed_prod_rdy_perf', type: 'double', label: 'Supplier Committed Production Ready Performance' },
  { name: '_iss_transit_lead_time_perf', type: 'double', label: 'ISS Transit Lead Time Performance' },
  { name: '_iss_custom_clear_perf', type: 'double', label: 'ISS Custom Clear Performance' },
  { name: '_rdd_eta', type: 'int64', label: 'RDD to ETA' },
  { name: '_crd_2_etd', type: 'int64', label: 'CRD to ETD' },
  { name: '_po_2_crd', type: 'int64', label: 'PO to CRD' },
  { name: '_actual_lead', type: 'double', label: 'Actual Lead' },
  { name: '_ship_focus_status', type: 'string', label: 'Ship Focus Status' },
  { name: '_health_check', type: 'string', label: 'Health Check' },
  { name: '_status', type: 'string', label: 'Status' },
  { name: '_reason_code', type: 'string', label: 'Reason Code' },
  { name: '_nbd_2_crd', type: 'double', label: 'NBD to CRD' },
  { name: '_nbd_2_eta', type: 'int64', label: 'NBD to ETA' },
  { name: '_avg_lt', type: 'double', label: 'Avg LT' },
  { name: '_pre_alert', type: 'string', label: 'Pre-alert' },
  { name: '_pack_type', type: 'string', label: 'Pack Type' },
  { name: '_delivery_location', type: 'string', label: 'Delivery Location' },
  { name: '_inbound_iss_job_no', type: 'string', label: 'Inbound ISS Job No.' },
  { name: '_outbound_iss_job_no', type: 'string', label: 'Outbound ISS Job No.' },
  { name: '_po_uom', type: 'string', label: 'PO UOM' },
  { name: '_dn', type: 'string', label: 'DN' },
  { name: '_spo_invoice_val_aed', type: 'double', label: 'SPO Invoice Value AED' },
  { name: '_cbm', type: 'double', label: 'Volume (CBM)' },
  { name: '_gw', type: 'double', label: 'Gross Weight (GW)' },
  { name: '_chw', type: 'double', label: 'Chargeable Weight (CHW)' },
  { name: '_qnty', type: 'double', label: 'Qty' },
  { name: '_container_no', type: 'string', label: 'Container No.' },
  { name: '_item_code', type: 'string', label: 'Item Code' },
  { name: '_po_line_status', type: 'string', label: 'PO Line Status' },
  { name: '_units_po_uom', type: 'int64', label: 'Units PO UOM' },
  { name: '_po_inner_qnty', type: 'double', label: 'PO Inner Qty' },
  { name: '_inner_qnty_shipped', type: 'double', label: 'Inner Qty Shipped' },
  { name: '_balance_outer_qnty', type: 'double', label: 'Balance Outer Qty' },
  { name: '_balance_inner_qnty', type: 'double', label: 'Balance Inner Qty' },
  { name: '_original_po_qty', type: 'double', label: 'Original PO Qty' },
  { name: '_po_outer_qty', type: 'double', label: 'PO Outer Qty' },
  { name: '_first_edd_po', type: 'dateTime', label: 'First EDD PO' },
  { name: '_current_edd_po', type: 'dateTime', label: 'Current EDD PO' },
  { name: '_first_edd_fo', type: 'dateTime', label: 'First EDD FO' },
  { name: '_current_edd_fo', type: 'dateTime', label: 'Current EDD FO' },
  { name: '_ptd', type: 'dateTime', label: 'PTD' },
  { name: '_pta', type: 'dateTime', label: 'PTA' },
  { name: '_final_expected_del_date', type: 'dateTime', label: 'Final Expected Delivery Date' },
  { name: '_response_shipment_id', type: 'string', label: 'Response Shipment ID' },
  { name: '_arrival_date_actual', type: 'dateTime', label: 'Arrival Date Actual' },
  { name: '_01_po_aknowledgment_expt', type: 'string', label: '01 PO Acknowledgment Exception' },
  { name: '_02_po_pickup_departure_expt', type: 'string', label: '02 PO Pickup Departure Exception' },
  { name: '_03_po_transit_expt', type: 'string', label: '03 PO Transit Exception' },
  { name: '_04_po_custom_clear_expt', type: 'string', label: '04 PO Custom Clear Exception' },
  { name: '_05_po_delivery_expt', type: 'string', label: '05 PO Delivery Exception' },
  { name: '_master_line', type: 'string', label: 'Master Line' },
  { name: '_06_expt_status', type: 'string', label: '06 Exception Status' },
  { name: '_eta_iss', type: 'dateTime', label: 'ETA ISS' },
  { name: '_etd_iss', type: 'dateTime', label: 'ETD ISS' },
  { name: '_arrival_date_full', type: 'dateTime', label: 'Arrival Date Full' },
  { name: '_arrival_date_fallback', type: 'dateTime', label: 'Arrival Date (Fallback)' },
  { name: '_departure_date_fallback', type: 'dateTime', label: 'Departure Date (Fallback)' },
  { name: '_port_of_discharge', type: 'string', label: 'Port of Discharge' },
  { name: '_port_of_discharge_name', type: 'string', label: 'Port of Discharge Name' },
  { name: '_origin_country_code', type: 'string', label: 'Origin Country Code' },
  { name: '_transport_mode', type: 'string', label: 'Transport Mode' },
  { name: '_slt_category', type: 'string', label: 'SLT Category' },
  { name: '_customs_declared_currency', type: 'string', label: 'Customs Declared Currency' },
  { name: '_direction', type: 'string', label: 'Direction' },
  { name: '_ptd_discrepancy_days', type: 'int64', label: 'PTD Discrepancy Days' },
  { name: '_pta_discrepancy_days', type: 'int64', label: 'PTA Discrepancy Days' },
  { name: '_pack_type_name', type: 'string', label: 'Pack Type Name' },
  { name: '_dep_discrepancy_days', type: 'int64', label: 'Departure Discrepancy Days' },
  { name: '_arr_discrepancy_days', type: 'int64', label: 'Arrival Discrepancy Days' },
  { name: '_eta_source', type: 'string', label: 'ETA Source' },
  { name: '_etd_source', type: 'string', label: 'ETD Source' },
  { name: '_ship_type', type: 'string', label: 'Ship Type' },
  { name: '_carrier_code', type: 'string', label: 'Carrier Code' },
  { name: '_focus_link', type: 'string', label: 'Focus Link' },
  { name: '_ptd_2_now', type: 'int64', label: 'PTD to Now' },
  { name: '_pickup_2_now', type: 'int64', label: 'Pickup to Now' },
  { name: '_crd_2_ptd', type: 'int64', label: 'CRD to PTD' },
  { name: '_ptd_2_now_bucket', type: 'string', label: 'PTD to Now Bucket' },
  { name: '_cur_location', type: 'string', label: 'Current Location' },
  { name: '_port_water', type: 'string', label: 'Port / Water' },
  { name: '_rdd_2_now', type: 'int64', label: 'RDD to Now' },
  { name: '_etd_2_crd', type: 'int64', label: 'ETD to CRD' },
  { name: '_rdd_2_pta', type: 'int64', label: 'RDD to PTA' },
  { name: '_air_sea_bucket', type: 'string', label: 'Air / Sea Bucket' },
  { name: '_ptd_2_crd', type: 'int64', label: 'PTD to CRD' },
  { name: '_del_2_ptd', type: 'int64', label: 'Delivery to PTD' },
  { name: '_del_2_crd', type: 'int64', label: 'Delivery to CRD' },
  { name: '_crd_status', type: 'string', label: 'CRD Status' },
  { name: '_pta_2_rdd', type: 'int64', label: 'PTA to RDD' },
  { name: '_nbd_2_pta_status', type: 'int64', label: 'NBD to PTA Status' },
  { name: '_etd_2_ptd', type: 'int64', label: 'ETD to PTD' },
  { name: '_focus_ship_id', type: 'int64', label: 'Focus Ship ID' },
  { name: '_eta_last_change', type: 'dateTime', label: 'ETA Last Change' },
  { name: '_etd_last_change', type: 'dateTime', label: 'ETD Last Change' },
  { name: '_effective_eta', type: 'dateTime', label: 'Effective ETA' },
  { name: '_eta_delay', type: 'double', label: 'ETA Delay' },
  { name: '_eta_delay_bucket', type: 'string', label: 'ETA Delay Bucket' },
  { name: '_del_from_etd', type: 'int64', label: 'Delivery from ETD' },
  { name: '_quote_date', type: 'dateTime', label: 'Quote Date' },
  { name: '_quote_status', type: 'string', label: 'Quote Status' },
  { name: '_quote_amount_usd', type: 'string', label: 'Quote Amount USD' },
  { name: '_quote_details_usd', type: 'string', label: 'Quote Details USD' },
  { name: '_quote_approve_date', type: 'dateTime', label: 'Quote Approve Date' },
  { name: '_quote_approve_details_usd', type: 'string', label: 'Quote Approve Details USD' },
  { name: '_quote_approve_amount_usd', type: 'string', label: 'Quote Approve Amount USD' },
  { name: '_nbd_2_arr', type: 'double', label: 'NBD to Arrival' },
  { name: '_crd_2_rdd', type: 'int64', label: 'CRD to RDD' },
  { name: '_ptd_from_crd', type: 'int64', label: 'PTD from CRD' },
  { name: '_etd_from_crd', type: 'int64', label: 'ETD from CRD' },
  { name: '_eta_2_nbd', type: 'int64', label: 'ETA to NBD' },
  { name: '_freight_order_comment', type: 'string', label: 'Freight Order Comment' },
  { name: '_quote_approve_amount_aed', type: 'double', label: 'Quote Approve Amount AED' },
  { name: '_lob', type: 'string', label: 'LOB' },
  { name: '_tranship_locode', type: 'string', label: 'Transship LOCODE' },
  { name: '_tranship_port_name', type: 'string', label: 'Transship Port Name' },
  { name: '_tranship_days', type: 'int64', label: 'Transship Days' },
  { name: '_tranship_vessel', type: 'string', label: 'Transship Vessel' },
  { name: '_etd_2_eta_alt', type: 'int64', label: 'ETD to ETA (Alt)' },
  { name: '_eta_2_del_alt', type: 'int64', label: 'ETA to Delivery (Alt)' },
  { name: '_crd_2_etd_alt', type: 'int64', label: 'CRD to ETD (Alt)' },
  { name: '_eta_2_pta', type: 'int64', label: 'ETA to PTA' },
  { name: '_nbd_2_eta_alt', type: 'int64', label: 'NBD to ETA (Alt)' },
  { name: '_crd_2_cur', type: 'int64', label: 'CRD to Current' },
  { name: '_eta_location', type: 'string', label: 'ETA Location' },
];

export const PO_COLUMN_BY_NAME: ReadonlyMap<string, PoColumn> = new Map(
  PO_COLUMNS.map((c) => [c.name, c])
);

/** The default view, in display order. */
export const DEFAULT_PO_COLUMNS: readonly string[] = [
  '_po_no_ekporef',
  '_line_no',
  '_master_line',
  '_supplier_name',
  '_po_need_by_date',
  '_po_status',
  '_client_name',
  '_branch_bu',
  '_item_code',
  '_commodity',
  '_po_creation_date',
  '_etd',
  '_eta',
  '_transport_mode',
  '_origin_country',
  '_destination_country_dest',
];

/**
 * Upper bound on columns per query. Power BI caps executeQueries at 1M values
 * and 15 MB per response; at ~3.4k rows 25 columns stays near 2.5 MB, leaving
 * room for the table to grow several-fold.
 */
export const MAX_PO_COLUMNS = 25;

/** Friendly label for a model column name; unknown names fall back to the raw name. */
export function columnLabel(name: string): string {
  return PO_COLUMN_BY_NAME.get(name)?.label ?? name;
}
