// Generated from the "Coms report" semantic model TMDL (table _PO_VIEW_), 2026-10-07.
// Regenerate when the model's columns change: export the model with
// `fab export "EMBEDDING PROD.Workspace/Coms report.SemanticModel"` and rebuild this list.

export type PoColumnType = 'string' | 'int64' | 'double' | 'dateTime';

export interface PoColumn {
  /** Model column name, also the DAX alias and the row key. */
  name: string;
  type: PoColumnType;
}

/**
 * Every column of `_PO_VIEW_`, in model order. The six calculated placeholders
 * `_tbd_* = 1` are left out on purpose: they are constant 1 in every row.
 */
export const PO_COLUMNS: readonly PoColumn[] = [
  { name: '_line_type', type: 'string' },
  { name: '_line_id', type: 'string' },
  { name: '_shipped', type: 'double' },
  { name: '_qnty_shipped_remaning', type: 'double' },
  { name: '_branch_bu', type: 'string' },
  { name: '_supplier_code', type: 'string' },
  { name: '_supplier_name', type: 'string' },
  { name: '_po_no_ekporef', type: 'string' },
  { name: '_po_remarks', type: 'string' },
  { name: '_commodity', type: 'string' },
  { name: '_incoterms', type: 'string' },
  { name: '_incoterms_desc', type: 'string' },
  { name: '_pr_appr_date', type: 'dateTime' },
  { name: '_po_app_date', type: 'dateTime' },
  { name: '_po_creation_date', type: 'dateTime' },
  { name: '_po_recd_date', type: 'dateTime' },
  { name: '_po_need_by_date', type: 'dateTime' },
  { name: '_line_no', type: 'int64' },
  { name: '_po_type', type: 'string' },
  { name: '_incoterms_fo', type: 'string' },
  { name: '_shipment_serial_iss_job', type: 'string' },
  { name: '_hbl_hawb', type: 'string' },
  { name: '_mbl_mawb', type: 'string' },
  { name: '_freight_unit_id', type: 'int64' },
  { name: '_fo_id', type: 'int64' },
  { name: '_fo_serial', type: 'string' },
  { name: '_shipment_link', type: 'string' },
  { name: '_eqpt_type', type: 'string' },
  { name: '_20_ft', type: 'int64' },
  { name: '_40_ft', type: 'int64' },
  { name: '_count_of_cont', type: 'int64' },
  { name: '_teus', type: 'int64' },
  { name: '_carrier', type: 'string' },
  { name: '_arrival_date', type: 'dateTime' },
  { name: '_del', type: 'dateTime' },
  { name: '_departure_date', type: 'dateTime' },
  { name: '_departure_date_actual', type: 'dateTime' },
  { name: '_crd_actual', type: 'dateTime' },
  { name: '_crd_estimated', type: 'dateTime' },
  { name: '_crd', type: 'dateTime' },
  { name: '_goods_cleared_origin', type: 'dateTime' },
  { name: '_goods_cleared_destination', type: 'dateTime' },
  { name: '_pickup_date', type: 'dateTime' },
  { name: '_cargo_ho', type: 'dateTime' },
  { name: '_eta', type: 'dateTime' },
  { name: '_eta_wakeo', type: 'dateTime' },
  { name: '_etd', type: 'dateTime' },
  { name: '_etd_wakeo', type: 'dateTime' },
  { name: '_full_etd', type: 'dateTime' },
  { name: '_pod_date', type: 'dateTime' },
  { name: '_do_date', type: 'dateTime' },
  { name: '_do_exp', type: 'dateTime' },
  { name: '_pr_number', type: 'string' },
  { name: '_pr_date', type: 'dateTime' },
  { name: '_req_status', type: 'string' },
  { name: '_spo_number', type: 'string' },
  { name: '_po_status', type: 'string' },
  { name: '_grn_no', type: 'string' },
  { name: '_grn_status', type: 'string' },
  { name: '_addl_po', type: 'string' },
  { name: '_addl_po_grn', type: 'string' },
  { name: '_days_delayed_eta', type: 'int64' },
  { name: '_days_delayed_etd', type: 'int64' },
  { name: '_etd_2_eta', type: 'int64' },
  { name: '_eta_2_del', type: 'int64' },
  { name: '_nbd_2_del', type: 'int64' },
  { name: '_client_id', type: 'int64' },
  { name: '_client_name', type: 'string' },
  { name: '_origin_port_pol', type: 'string' },
  { name: '_origin_port_name', type: 'string' },
  { name: '_origin_country', type: 'string' },
  { name: '_origin_region_org_reg', type: 'string' },
  { name: '_destination_port_code_dest', type: 'string' },
  { name: '_destination_port_name_dest', type: 'string' },
  { name: '_destination_country_code_dest', type: 'string' },
  { name: '_destination_country_dest', type: 'string' },
  { name: '_destination_region_reg', type: 'string' },
  { name: '_ship_remarks_updates', type: 'string' },
  { name: '_ship_billing_remarks', type: 'string' },
  { name: '_routed_by', type: 'string' },
  { name: '_aux_charge_type', type: 'string' },
  { name: '_aux_charge_form_no', type: 'string' },
  { name: '_org_charges_aed', type: 'double' },
  { name: '_dest_charges_aed', type: 'double' },
  { name: '_frt_charges_aed', type: 'double' },
  { name: '_aux_charges_aed', type: 'double' },
  { name: '_p2p_value_aed', type: 'double' },
  { name: '_total_charges_aed', type: 'double' },
  { name: '_org_charges_usd', type: 'double' },
  { name: '_dest_charges_usd', type: 'double' },
  { name: '_frt_charges_usd', type: 'double' },
  { name: '_aux_charges_usd', type: 'double' },
  { name: '_p2p_value_usd', type: 'double' },
  { name: '_total_charges_usd', type: 'double' },
  { name: '_invoice_no', type: 'string' },
  { name: '_invoice_issue_date', type: 'string' },
  { name: '_addl_issued_invoices', type: 'string' },
  { name: '_addl_invoice_issue_date', type: 'string' },
  { name: '_customs_invoice_aed', type: 'double' },
  { name: '_customs_invoice_usd', type: 'double' },
  { name: '_billing_status', type: 'string' },
  { name: '_mode', type: 'string' },
  { name: '_days_order_placement_lt', type: 'int64' },
  { name: '_days_supplier_production_lt', type: 'int64' },
  { name: '_days_custom_clearance_lt', type: 'int64' },
  { name: '_days_iss_cont_booking_lt', type: 'int64' },
  { name: '_days_transit_lt', type: 'int64' },
  { name: '_e2e_total_lt', type: 'int64' },
  { name: '_supplier_lead_time', type: 'int64' },
  { name: '_country_lead_time', type: 'int64' },
  { name: '_ontime_order_placement_perf', type: 'double' },
  { name: '_days_total_comm_perf', type: 'double' },
  { name: '_e2e_total_lead_time_perf', type: 'double' },
  { name: '_iss_cont_booking_perf', type: 'double' },
  { name: '_supplier_committed_prod_rdy_perf', type: 'double' },
  { name: '_iss_transit_lead_time_perf', type: 'double' },
  { name: '_iss_custom_clear_perf', type: 'double' },
  { name: '_rdd_eta', type: 'int64' },
  { name: '_crd_2_etd', type: 'int64' },
  { name: '_po_2_crd', type: 'int64' },
  { name: '_actual_lead', type: 'double' },
  { name: '_ship_focus_status', type: 'string' },
  { name: '_health_check', type: 'string' },
  { name: '_status', type: 'string' },
  { name: '_reason_code', type: 'string' },
  { name: '_nbd_2_crd', type: 'double' },
  { name: '_nbd_2_eta', type: 'int64' },
  { name: '_avg_lt', type: 'double' },
  { name: '_pre_alert', type: 'string' },
  { name: '_pack_type', type: 'string' },
  { name: '_delivery_location', type: 'string' },
  { name: '_inbound_iss_job_no', type: 'string' },
  { name: '_outbound_iss_job_no', type: 'string' },
  { name: '_po_uom', type: 'string' },
  { name: '_dn', type: 'string' },
  { name: '_spo_invoice_val_aed', type: 'double' },
  { name: '_cbm', type: 'double' },
  { name: '_gw', type: 'double' },
  { name: '_chw', type: 'double' },
  { name: '_qnty', type: 'double' },
  { name: '_container_no', type: 'string' },
  { name: '_item_code', type: 'string' },
  { name: '_po_line_status', type: 'string' },
  { name: '_units_po_uom', type: 'int64' },
  { name: '_po_inner_qnty', type: 'double' },
  { name: '_inner_qnty_shipped', type: 'double' },
  { name: '_balance_outer_qnty', type: 'double' },
  { name: '_balance_inner_qnty', type: 'double' },
  { name: '_original_po_qty', type: 'double' },
  { name: '_po_outer_qty', type: 'double' },
  { name: '_first_edd_po', type: 'dateTime' },
  { name: '_current_edd_po', type: 'dateTime' },
  { name: '_first_edd_fo', type: 'dateTime' },
  { name: '_current_edd_fo', type: 'dateTime' },
  { name: '_ptd', type: 'dateTime' },
  { name: '_pta', type: 'dateTime' },
  { name: '_final_expected_del_date', type: 'dateTime' },
  { name: '_response_shipment_id', type: 'string' },
  { name: '_arrival_date_actual', type: 'dateTime' },
  { name: '_01_po_aknowledgment_expt', type: 'string' },
  { name: '_02_po_pickup_departure_expt', type: 'string' },
  { name: '_03_po_transit_expt', type: 'string' },
  { name: '_04_po_custom_clear_expt', type: 'string' },
  { name: '_05_po_delivery_expt', type: 'string' },
  { name: '_master_line', type: 'string' },
  { name: '_06_expt_status', type: 'string' },
  { name: '_eta_iss', type: 'dateTime' },
  { name: '_etd_iss', type: 'dateTime' },
  { name: '_arrival_date_full', type: 'dateTime' },
  { name: '_arrival_date_fallback', type: 'dateTime' },
  { name: '_departure_date_fallback', type: 'dateTime' },
  { name: '_port_of_discharge', type: 'string' },
  { name: '_port_of_discharge_name', type: 'string' },
  { name: '_origin_country_code', type: 'string' },
  { name: '_transport_mode', type: 'string' },
  { name: '_slt_category', type: 'string' },
  { name: '_customs_declared_currency', type: 'string' },
  { name: '_direction', type: 'string' },
  { name: '_ptd_discrepancy_days', type: 'int64' },
  { name: '_pta_discrepancy_days', type: 'int64' },
  { name: '_pack_type_name', type: 'string' },
  { name: '_dep_discrepancy_days', type: 'int64' },
  { name: '_arr_discrepancy_days', type: 'int64' },
  { name: '_eta_source', type: 'string' },
  { name: '_etd_source', type: 'string' },
  { name: '_ship_type', type: 'string' },
  { name: '_carrier_code', type: 'string' },
  { name: '_focus_link', type: 'string' },
  { name: '_ptd_2_now', type: 'int64' },
  { name: '_pickup_2_now', type: 'int64' },
  { name: '_crd_2_ptd', type: 'int64' },
  { name: '_ptd_2_now_bucket', type: 'string' },
  { name: '_cur_location', type: 'string' },
  { name: '_port_water', type: 'string' },
  { name: '_rdd_2_now', type: 'int64' },
  { name: '_etd_2_crd', type: 'int64' },
  { name: '_rdd_2_pta', type: 'int64' },
  { name: '_air_sea_bucket', type: 'string' },
  { name: '_ptd_2_crd', type: 'int64' },
  { name: '_del_2_ptd', type: 'int64' },
  { name: '_del_2_crd', type: 'int64' },
  { name: '_crd_status', type: 'string' },
  { name: '_pta_2_rdd', type: 'int64' },
  { name: '_nbd_2_pta_status', type: 'int64' },
  { name: '_etd_2_ptd', type: 'int64' },
  { name: '_focus_ship_id', type: 'int64' },
  { name: '_eta_last_change', type: 'dateTime' },
  { name: '_etd_last_change', type: 'dateTime' },
  { name: '_effective_eta', type: 'dateTime' },
  { name: '_eta_delay', type: 'double' },
  { name: '_eta_delay_bucket', type: 'string' },
  { name: '_del_from_etd', type: 'int64' },
  { name: '_quote_date', type: 'dateTime' },
  { name: '_quote_status', type: 'string' },
  { name: '_quote_amount_usd', type: 'string' },
  { name: '_quote_details_usd', type: 'string' },
  { name: '_quote_approve_date', type: 'dateTime' },
  { name: '_quote_approve_details_usd', type: 'string' },
  { name: '_quote_approve_amount_usd', type: 'string' },
  { name: '_nbd_2_arr', type: 'double' },
  { name: '_crd_2_rdd', type: 'int64' },
  { name: '_ptd_from_crd', type: 'int64' },
  { name: '_etd_from_crd', type: 'int64' },
  { name: '_eta_2_nbd', type: 'int64' },
  { name: '_freight_order_comment', type: 'string' },
  { name: '_quote_approve_amount_aed', type: 'double' },
  { name: '_lob', type: 'string' },
  { name: '_tranship_locode', type: 'string' },
  { name: '_tranship_port_name', type: 'string' },
  { name: '_tranship_days', type: 'int64' },
  { name: '_tranship_vessel', type: 'string' },
  { name: '_etd_2_eta_alt', type: 'int64' },
  { name: '_eta_2_del_alt', type: 'int64' },
  { name: '_crd_2_etd_alt', type: 'int64' },
  { name: '_eta_2_pta', type: 'int64' },
  { name: '_nbd_2_eta_alt', type: 'int64' },
  { name: '_crd_2_cur', type: 'int64' },
  { name: '_eta_location', type: 'string' },
];

export const PO_COLUMN_BY_NAME: ReadonlyMap<string, PoColumn> = new Map(
  PO_COLUMNS.map((c) => [c.name, c])
);

/** The default view, in display order. */
export const DEFAULT_PO_COLUMNS: readonly string[] = [
  '_po_no_ekporef',
  '_line_no',
  '_master_line',
  '_supplier_name',
  '_po_need_by_date',
  '_po_status',
  '_client_name',
  '_branch_bu',
  '_item_code',
  '_commodity',
  '_po_creation_date',
  '_etd',
  '_eta',
  '_transport_mode',
  '_origin_country',
  '_destination_country_dest',
];

/**
 * Upper bound on columns per query. Power BI caps executeQueries at 1M values
 * and ~15 MB per response; at ~3.4k rows a full-width row is ~8.8 kB, so 60
 * columns stays near 6 MB with room for the table to grow.
 */
export const MAX_PO_COLUMNS = 60;

/** '_po_no_ekporef' → 'PO NO EKPOREF'. */
export function columnLabel(name: string): string {
  return name.replace(/^_+/, '').split('_').filter(Boolean).join(' ').toUpperCase();
}
